/**
 * Generates expanded PakDataKit data files.
 * Run: node scripts/generate-data.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, '..', 'data');

const PROVINCE_NAMES = {
  JK: 'Azad Jammu and Kashmir',
  BA: 'Balochistan',
  NA: 'Gilgit-Baltistan',
  IS: 'Islamabad Capital Territory',
  NW: 'Khyber Pakhtunkhwa',
  PB: 'Punjab',
  SD: 'Sindh',
};

/** All 169+ administrative districts (2023–2024). */
const DISTRICTS_RAW = [
  ['Abbottabad', 'NW'],
  ['Astore', 'NA'],
  ['Attock', 'PB'],
  ['Awaran', 'BA'],
  ['Badin', 'SD'],
  ['Bagh', 'JK'],
  ['Bahawalnagar', 'PB'],
  ['Bahawalpur', 'PB'],
  ['Bajaur', 'NW'],
  ['Bannu', 'NW'],
  ['Barkhan', 'BA'],
  ['Batagram', 'NW'],
  ['Bhakkar', 'PB'],
  ['Bhimber', 'JK'],
  ['Buner', 'NW'],
  ['Chagai', 'BA'],
  ['Chakwal', 'PB'],
  ['Chaman', 'BA'],
  ['Charsadda', 'NW'],
  ['Chiniot', 'PB'],
  ['Dadu', 'SD'],
  ['Dera Bugti', 'BA'],
  ['Dera Ghazi Khan', 'PB'],
  ['Dera Ismail Khan', 'NW'],
  ['Diamer', 'NA'],
  ['Duki', 'BA'],
  ['Faisalabad', 'PB'],
  ['Ghanche', 'NA'],
  ['Ghizer', 'NA'],
  ['Ghotki', 'SD'],
  ['Gilgit', 'NA'],
  ['Gujranwala', 'PB'],
  ['Gujrat', 'PB'],
  ['Gwadar', 'BA'],
  ['Hafizabad', 'PB'],
  ['Hangu', 'NW'],
  ['Haripur', 'NW'],
  ['Harnai', 'BA'],
  ['Hatian Bala', 'JK'],
  ['Haveli', 'JK'],
  ['Hunza', 'NA'],
  ['Hyderabad', 'SD'],
  ['Islamabad', 'IS'],
  ['Jacobabad', 'SD'],
  ['Jaffarabad', 'BA'],
  ['Jamshoro', 'SD'],
  ['Jhal Magsi', 'BA'],
  ['Jhang', 'PB'],
  ['Jhelum', 'PB'],
  ['Kachhi', 'BA'],
  ['Kalat', 'BA'],
  ['Karachi Central', 'SD'],
  ['Karachi East', 'SD'],
  ['Karachi South', 'SD'],
  ['Karachi West', 'SD'],
  ['Karak', 'NW'],
  ['Kashmore', 'SD'],
  ['Kasur', 'PB'],
  ['Keamari', 'SD'],
  ['Kech', 'BA'],
  ['Khairpur', 'SD'],
  ['Khanewal', 'PB'],
  ['Kharan', 'BA'],
  ['Kharmang', 'NA'],
  ['Khushab', 'PB'],
  ['Khuzdar', 'BA'],
  ['Khyber', 'NW'],
  ['Killa Abdullah', 'BA'],
  ['Killa Saifullah', 'BA'],
  ['Kohat', 'NW'],
  ['Kohlu', 'BA'],
  ['Kolai-Palas', 'NW'],
  ['Korangi', 'SD'],
  ['Kot Addu', 'PB'],
  ['Kotli', 'JK'],
  ['Kurram', 'NW'],
  ['Lahore', 'PB'],
  ['Lakki Marwat', 'NW'],
  ['Larkana', 'SD'],
  ['Lasbela', 'BA'],
  ['Layyah', 'PB'],
  ['Lodhran', 'PB'],
  ['Loralai', 'BA'],
  ['Lower Chitral', 'NW'],
  ['Lower Dir', 'NW'],
  ['Lower Kohistan', 'NW'],
  ['Malakand', 'NW'],
  ['Malir', 'SD'],
  ['Mandi Bahauddin', 'PB'],
  ['Mansehra', 'NW'],
  ['Mardan', 'NW'],
  ['Mastung', 'BA'],
  ['Matiari', 'SD'],
  ['Mianwali', 'PB'],
  ['Mirpur', 'JK'],
  ['Mirpur Khas', 'SD'],
  ['Mohmand', 'NW'],
  ['Multan', 'PB'],
  ['Murree', 'PB'],
  ['Musakhel', 'BA'],
  ['Muzaffarabad', 'JK'],
  ['Muzaffargarh', 'PB'],
  ['Nagar', 'NA'],
  ['Nankana Sahib', 'PB'],
  ['Narowal', 'PB'],
  ['Nasirabad', 'BA'],
  ['Naushahro Feroze', 'SD'],
  ['Neelam', 'JK'],
  ['North Waziristan', 'NW'],
  ['Nowshera', 'NW'],
  ['Nushki', 'BA'],
  ['Okara', 'PB'],
  ['Orakzai', 'NW'],
  ['Pakpattan', 'PB'],
  ['Panjgur', 'BA'],
  ['Peshawar', 'NW'],
  ['Pishin', 'BA'],
  ['Poonch', 'JK'],
  ['Qambar Shahdadkot', 'SD'],
  ['Quetta', 'BA'],
  ['Rahim Yar Khan', 'PB'],
  ['Rajanpur', 'PB'],
  ['Rawalpindi', 'PB'],
  ['Sahiwal', 'PB'],
  ['Sanghar', 'SD'],
  ['Sargodha', 'PB'],
  ['Shaheed Benazir Abad', 'SD'],
  ['Shangla', 'NW'],
  ['Sheerani', 'BA'],
  ['Sheikhupura', 'PB'],
  ['Shigar', 'NA'],
  ['Shikarpur', 'SD'],
  ['Sialkot', 'PB'],
  ['Sibi', 'BA'],
  ['Skardu', 'NA'],
  ['Sohbatpur', 'BA'],
  ['South Waziristan', 'NW'],
  ['Sudhnuti', 'JK'],
  ['Sujawal', 'SD'],
  ['Sukkur', 'SD'],
  ['Surab', 'BA'],
  ['Swabi', 'NW'],
  ['Swat', 'NW'],
  ['Talagang', 'PB'],
  ['Tando Allahyar', 'SD'],
  ['Tando Muhammad Khan', 'SD'],
  ['Tank', 'NW'],
  ['Tharparkar', 'SD'],
  ['Thatta', 'SD'],
  ['Toba Tek Singh', 'PB'],
  ['Tor Ghar', 'NW'],
  ['Umerkot', 'SD'],
  ['Upper Chitral', 'NW'],
  ['Upper Dir', 'NW'],
  ['Upper Kohistan', 'NW'],
  ['Vehari', 'PB'],
  ['Washuk', 'BA'],
  ['Wazirabad', 'PB'],
  ['Zhob', 'BA'],
  ['Ziarat', 'BA'],
  ['Darel', 'NA'],
  ['Gupis-Yasin', 'NA'],
  ['Tangir', 'NA'],
  ['Rondu', 'NA'],
  ['Hunza', 'NA'],
  ['Shigar', 'NA'],
  ['Ghizer', 'NA'],
  ['Ghanche', 'NA'],
  ['Astore', 'NA'],
  ['Nagar', 'NA'],
  ['Kharmang', 'NA'],
];

const districts = DISTRICTS_RAW.map(([district, code]) => ({
  district,
  province: PROVINCE_NAMES[code],
})).sort((a, b) => a.district.localeCompare(b.district));

const CORE_CITIES = [
  ['Karachi', 'Sindh'],
  ['Lahore', 'Punjab'],
  ['Islamabad', 'Islamabad Capital Territory'],
  ['Rawalpindi', 'Punjab'],
  ['Faisalabad', 'Punjab'],
  ['Multan', 'Punjab'],
  ['Hyderabad', 'Sindh'],
  ['Peshawar', 'Khyber Pakhtunkhwa'],
  ['Quetta', 'Balochistan'],
  ['Gujranwala', 'Punjab'],
  ['Sialkot', 'Punjab'],
  ['Sukkur', 'Sindh'],
];

/** Top 150 cities by significance (district HQs + major urban centres). */
const citiesMap = new Map();

for (const [city, province] of CORE_CITIES) {
  citiesMap.set(city, province);
}

const additionalCities = [
  ['Wah Cantonment', 'Punjab'],
  ['Mingora', 'Khyber Pakhtunkhwa'],
  ['Kamoke', 'Punjab'],
  ['Burewala', 'Punjab'],
  ['Gojra', 'Punjab'],
  ['Jaranwala', 'Punjab'],
  ['Chishtian', 'Punjab'],
  ['Kharian', 'Punjab'],
  ['Kandhkot', 'Sindh'],
  ['Hasilpur', 'Punjab'],
  ['Arifwala', 'Punjab'],
  ['Kamalia', 'Punjab'],
  ['Chichawatni', 'Punjab'],
  ['Mian Channu', 'Punjab'],
  ['Bhalwal', 'Punjab'],
  ['Sadiqabad', 'Punjab'],
  ['Shahdadkot', 'Sindh'],
  ['Hub', 'Balochistan'],
  ['Rawalakot', 'Azad Jammu and Kashmir'],
  ['Shahdadpur', 'Sindh'],
  ['Parachinar', 'Khyber Pakhtunkhwa'],
  ['Taxila', 'Punjab'],
  ['Bhawana', 'Punjab'],
  ['Daska', 'Punjab'],
  ['Pasrur', 'Punjab'],
  ['Zafarwal', 'Punjab'],
  ['Shakargarh', 'Punjab'],
  ['Phalia', 'Punjab'],
  ['Kot Momin', 'Punjab'],
  ['Pir Mahal', 'Punjab'],
  ['Khanpur', 'Punjab'],
  ['Liaquatpur', 'Punjab'],
  ['Fort Abbas', 'Punjab'],
  ['Haroonabad', 'Punjab'],
  ['Chunian', 'Punjab'],
  ['Pattoki', 'Punjab'],
  ['Renala Khurd', 'Punjab'],
  ['Depalpur', 'Punjab'],
  ['Dunyapur', 'Punjab'],
  ['Ahmadpur East', 'Punjab'],
  ['Yazman', 'Punjab'],
  ['Rojhan', 'Punjab'],
  ['Jampur', 'Punjab'],
  ['Kot Radha Kishan', 'Punjab'],
  ['Shahkot', 'Punjab'],
  ['Samundri', 'Punjab'],
  ['Tandlianwala', 'Punjab'],
  ['Kot Abdul Malik', 'Punjab'],
  ['Nawabshah', 'Sindh'],
  ['Chitral', 'Khyber Pakhtunkhwa'],
  ['Turbat', 'Balochistan'],
  ['Defence', 'Sindh'],
  ['Clifton', 'Sindh'],
  ['Landhi', 'Sindh'],
  ['Orangi', 'Sindh'],
  ['Gulshan-e-Iqbal', 'Sindh'],
  ['Nazimabad', 'Sindh'],
  ['Saddar', 'Sindh'],
  ['Kotri', 'Sindh'],
  ['Hala', 'Sindh'],
  ['Moro', 'Sindh'],
  ['Mehrabpur', 'Sindh'],
  ['Ratodero', 'Sindh'],
  ['Kandiaro', 'Sindh'],
  ['Mithi', 'Sindh'],
  ['Diplo', 'Sindh'],
  ['Chhor', 'Sindh'],
  ['Khipro', 'Sindh'],
  ['Sanghar City', 'Sindh'],
  ['Khairpur Nathan Shah', 'Sindh'],
  ['Sehwan', 'Sindh'],
  ['Ranipur', 'Sindh'],
  ['Gambat', 'Sindh'],
  ['Havelian', 'Khyber Pakhtunkhwa'],
  ['Timergara', 'Khyber Pakhtunkhwa'],
  ['Batkhela', 'Khyber Pakhtunkhwa'],
  ['Daggar', 'Khyber Pakhtunkhwa'],
  ['Alpuri', 'Khyber Pakhtunkhwa'],
  ['Bahrain', 'Khyber Pakhtunkhwa'],
  ['Kalam', 'Khyber Pakhtunkhwa'],
  ['Dir', 'Khyber Pakhtunkhwa'],
  ['Landi Kotal', 'Khyber Pakhtunkhwa'],
  ['Wana', 'Khyber Pakhtunkhwa'],
  ['Miranshah', 'Khyber Pakhtunkhwa'],
  ['Khaar', 'Khyber Pakhtunkhwa'],
  ['Ghalanai', 'Khyber Pakhtunkhwa'],
  ['Kalaya', 'Khyber Pakhtunkhwa'],
  ['Athmuqam', 'Azad Jammu and Kashmir'],
  ['Palandri', 'Azad Jammu and Kashmir'],
  ['Bagh City', 'Azad Jammu and Kashmir'],
  ['Hattian Bala Town', 'Azad Jammu and Kashmir'],
  ['Aliabad', 'Gilgit-Baltistan'],
  ['Khaplu', 'Gilgit-Baltistan'],
  ['Gahkuch', 'Gilgit-Baltistan'],
  ['Chilas', 'Gilgit-Baltistan'],
  ['Uthal', 'Balochistan'],
  ['Dalbandin', 'Balochistan'],
  ['Khuzdar City', 'Balochistan'],
  ['Dera Murad Jamali', 'Balochistan'],
  ['Dera Allah Yar', 'Balochistan'],
  ['Sibi Town', 'Balochistan'],
  ['Loralai Town', 'Balochistan'],
  ['Zhob City', 'Balochistan'],
  ['Chaman Town', 'Balochistan'],
  ['Pishin Town', 'Balochistan'],
  ['Mastung Town', 'Balochistan'],
  ['Kalat Town', 'Balochistan'],
  ['Pasni', 'Balochistan'],
  ['Ormara', 'Balochistan'],
  ['Jiwani', 'Balochistan'],
  ['Bela', 'Balochistan'],
  ['Winder', 'Balochistan'],
  ['Gaddani', 'Balochistan'],
  ['Kohlu Town', 'Balochistan'],
  ['Dhadar', 'Balochistan'],
  ['Sohbatpur Town', 'Balochistan'],
  ['Gulberg', 'Punjab'],
  ['Model Town', 'Punjab'],
  ['Cantt', 'Punjab'],
  ['Satiana', 'Punjab'],
  ['Shorkot', 'Punjab'],
  ['Kabirwala', 'Punjab'],
  ['Mailsi', 'Punjab'],
  ['Vehari City', 'Punjab'],
  ['Burewala City', 'Punjab'],
  ['Chak Jhumra', 'Punjab'],
  ['Jaranwala City', 'Punjab'],
  ['Sammundri', 'Punjab'],
  ['Khurrianwala', 'Punjab'],
  ['Sangla Hill', 'Punjab'],
  ['Shahpur', 'Punjab'],
  ['Kallar Kahar', 'Punjab'],
  ['Talagang City', 'Punjab'],
  ['Lawa', 'Punjab'],
  ['Pind Dadan Khan', 'Punjab'],
  ['Dina', 'Punjab'],
  ['Sohawa', 'Punjab'],
  ['Gujar Khan', 'Punjab'],
  ['Kallar Syedan', 'Punjab'],
  ['Kahuta', 'Punjab'],
  ['Kotli Loharan', 'Punjab'],
  ['Daska City', 'Punjab'],
  ['Wazirabad City', 'Punjab'],
  ['Ali Pur Chattha', 'Punjab'],
  ['Hujra Shah Muqeem', 'Punjab'],
  ['Renala Khurd City', 'Punjab'],
  ['Okara City', 'Punjab'],
  ['Renala Khurd', 'Punjab'],
];

for (const [city, province] of additionalCities) {
  if (!citiesMap.has(city)) {
    citiesMap.set(city, province);
  }
}

// Alias common names
const aliases = [
  ['Nawabshah', 'Shaheed Benazir Abad', 'Sindh'],
  ['Neelum Valley', 'Neelam', 'Azad Jammu and Kashmir'],
];
for (const [alias, canonical, province] of aliases) {
  if (citiesMap.has(canonical) && !citiesMap.has(alias)) {
    citiesMap.set(alias, province);
  }
}

let cities = [...citiesMap.entries()]
  .map(([city, province]) => ({ city, province }))
  .sort((a, b) => a.city.localeCompare(b.city));

if (cities.length > 150) {
  const coreSet = new Set(CORE_CITIES.map(([c]) => c));
  const core = cities.filter((c) => coreSet.has(c.city));
  const rest = cities.filter((c) => !coreSet.has(c.city));
  cities = [...core, ...rest].slice(0, 150);
}

/** Major postal codes — GPO + key areas. primary=true is default for getPostalCode(). */
const POSTAL_CODES = [
  // Islamabad & Rawalpindi
  { city: 'Islamabad', postalCode: '44000', area: 'Islamabad GPO', primary: true },
  { city: 'Rawalpindi', postalCode: '46000', area: 'Rawalpindi GPO', primary: true },
  { city: 'Rawalpindi', postalCode: '46300', area: 'Satellite Town' },
  { city: 'Murree', postalCode: '47150', area: 'Murree GPO', primary: true },
  { city: 'Taxila', postalCode: '47040', area: 'Taxila GPO', primary: true },
  // Punjab major
  { city: 'Lahore', postalCode: '54000', area: 'Lahore GPO', primary: true },
  { city: 'Lahore', postalCode: '54660', area: 'Gulberg' },
  { city: 'Lahore', postalCode: '54700', area: 'Model Town' },
  { city: 'Lahore', postalCode: '54810', area: 'Lahore Cantt' },
  { city: 'Lahore', postalCode: '54570', area: 'Iqbal Town' },
  { city: 'Faisalabad', postalCode: '38000', area: 'Faisalabad GPO', primary: true },
  { city: 'Multan', postalCode: '60000', area: 'Multan GPO', primary: true },
  { city: 'Gujranwala', postalCode: '52250', area: 'Gujranwala GPO', primary: true },
  { city: 'Sialkot', postalCode: '51310', area: 'Sialkot GPO', primary: true },
  { city: 'Sargodha', postalCode: '40100', area: 'Sargodha GPO', primary: true },
  { city: 'Bahawalpur', postalCode: '63100', area: 'Bahawalpur GPO', primary: true },
  { city: 'Sheikhupura', postalCode: '39350', area: 'Sheikhupura GPO', primary: true },
  { city: 'Gujrat', postalCode: '50700', area: 'Gujrat GPO', primary: true },
  { city: 'Jhang', postalCode: '35200', area: 'Jhang GPO', primary: true },
  { city: 'Sahiwal', postalCode: '57000', area: 'Sahiwal GPO', primary: true },
  { city: 'Okara', postalCode: '56300', area: 'Okara GPO', primary: true },
  { city: 'Kasur', postalCode: '55050', area: 'Kasur GPO', primary: true },
  { city: 'Dera Ghazi Khan', postalCode: '32200', area: 'DG Khan GPO', primary: true },
  { city: 'Muzaffargarh', postalCode: '34200', area: 'Muzaffargarh GPO', primary: true },
  { city: 'Rahim Yar Khan', postalCode: '64200', area: 'RY Khan GPO', primary: true },
  { city: 'Bahawalnagar', postalCode: '62300', area: 'Bahawalnagar GPO', primary: true },
  { city: 'Khanewal', postalCode: '58150', area: 'Khanewal GPO', primary: true },
  { city: 'Vehari', postalCode: '61100', area: 'Vehari GPO', primary: true },
  { city: 'Pakpattan', postalCode: '57400', area: 'Pakpattan GPO', primary: true },
  { city: 'Chiniot', postalCode: '35400', area: 'Chiniot GPO', primary: true },
  { city: 'Hafizabad', postalCode: '52110', area: 'Hafizabad GPO', primary: true },
  { city: 'Mandi Bahauddin', postalCode: '50400', area: 'Mandi Bahauddin GPO', primary: true },
  { city: 'Jhelum', postalCode: '49600', area: 'Jhelum GPO', primary: true },
  { city: 'Attock', postalCode: '43600', area: 'Attock GPO', primary: true },
  { city: 'Chakwal', postalCode: '48800', area: 'Chakwal GPO', primary: true },
  { city: 'Mianwali', postalCode: '42200', area: 'Mianwali GPO', primary: true },
  { city: 'Bhakkar', postalCode: '30000', area: 'Bhakkar GPO', primary: true },
  { city: 'Khushab', postalCode: '41000', area: 'Khushab GPO', primary: true },
  { city: 'Narowal', postalCode: '51600', area: 'Narowal GPO', primary: true },
  { city: 'Nankana Sahib', postalCode: '39100', area: 'Nankana Sahib GPO', primary: true },
  { city: 'Toba Tek Singh', postalCode: '36050', area: 'TTS GPO', primary: true },
  { city: 'Lodhran', postalCode: '59320', area: 'Lodhran GPO', primary: true },
  { city: 'Layyah', postalCode: '31200', area: 'Layyah GPO', primary: true },
  { city: 'Rajanpur', postalCode: '33500', area: 'Rajanpur GPO', primary: true },
  { city: 'Wazirabad', postalCode: '52000', area: 'Wazirabad GPO', primary: true },
  { city: 'Talagang', postalCode: '48100', area: 'Talagang GPO', primary: true },
  { city: 'Kot Addu', postalCode: '34050', area: 'Kot Addu GPO', primary: true },
  // Sindh
  { city: 'Karachi', postalCode: '74200', area: 'Karachi GPO', primary: true },
  { city: 'Karachi', postalCode: '74000', area: 'Karachi City GPO' },
  { city: 'Karachi', postalCode: '74400', area: 'Karachi Saddar GPO' },
  { city: 'Karachi', postalCode: '74800', area: 'New Town GPO' },
  { city: 'Karachi', postalCode: '74700', area: 'Al-Hydri GPO' },
  { city: 'Karachi', postalCode: '75500', area: 'Defence' },
  { city: 'Karachi', postalCode: '75600', area: 'Clifton' },
  { city: 'Karachi', postalCode: '75300', area: 'Gulshan-e-Iqbal' },
  { city: 'Karachi', postalCode: '74600', area: 'Nazimabad' },
  { city: 'Karachi', postalCode: '74900', area: 'Korangi' },
  { city: 'Karachi', postalCode: '75950', area: 'Federal B Area' },
  { city: 'Hyderabad', postalCode: '71000', area: 'Hyderabad GPO', primary: true },
  { city: 'Sukkur', postalCode: '65200', area: 'Sukkur GPO', primary: true },
  { city: 'Larkana', postalCode: '77150', area: 'Larkana GPO', primary: true },
  { city: 'Nawabshah', postalCode: '67450', area: 'Nawabshah GPO', primary: true },
  { city: 'Mirpur Khas', postalCode: '69000', area: 'Mirpur Khas GPO', primary: true },
  { city: 'Jacobabad', postalCode: '79000', area: 'Jacobabad GPO', primary: true },
  { city: 'Shikarpur', postalCode: '78100', area: 'Shikarpur GPO', primary: true },
  { city: 'Dadu', postalCode: '76200', area: 'Dadu GPO', primary: true },
  { city: 'Badin', postalCode: '72220', area: 'Badin GPO', primary: true },
  { city: 'Thatta', postalCode: '73020', area: 'Thatta GPO', primary: true },
  { city: 'Sanghar', postalCode: '68100', area: 'Sanghar GPO', primary: true },
  { city: 'Umerkot', postalCode: '69100', area: 'Umerkot GPO', primary: true },
  { city: 'Tharparkar', postalCode: '69230', area: 'Mithi GPO', primary: true },
  { city: 'Jamshoro', postalCode: '76080', area: 'Jamshoro GPO', primary: true },
  { city: 'Matiari', postalCode: '70100', area: 'Matiari GPO', primary: true },
  { city: 'Khairpur', postalCode: '66020', area: 'Khairpur GPO', primary: true },
  { city: 'Ghotki', postalCode: '65110', area: 'Ghotki GPO', primary: true },
  { city: 'Kashmore', postalCode: '79200', area: 'Kashmore GPO', primary: true },
  { city: 'Sujawal', postalCode: '73220', area: 'Sujawal GPO', primary: true },
  // KPK
  { city: 'Peshawar', postalCode: '25000', area: 'Peshawar GPO', primary: true },
  { city: 'Mardan', postalCode: '23200', area: 'Mardan GPO', primary: true },
  { city: 'Abbottabad', postalCode: '22010', area: 'Abbottabad GPO', primary: true },
  { city: 'Kohat', postalCode: '26000', area: 'Kohat GPO', primary: true },
  { city: 'Bannu', postalCode: '28100', area: 'Bannu GPO', primary: true },
  { city: 'Swat', postalCode: '19200', area: 'Mingora GPO', primary: true },
  { city: 'Mansehra', postalCode: '21300', area: 'Mansehra GPO', primary: true },
  { city: 'Dera Ismail Khan', postalCode: '29120', area: 'DI Khan GPO', primary: true },
  { city: 'Nowshera', postalCode: '24100', area: 'Nowshera GPO', primary: true },
  { city: 'Swabi', postalCode: '23430', area: 'Swabi GPO', primary: true },
  { city: 'Charsadda', postalCode: '24420', area: 'Charsadda GPO', primary: true },
  { city: 'Haripur', postalCode: '22620', area: 'Haripur GPO', primary: true },
  { city: 'Hangu', postalCode: '26190', area: 'Hangu GPO', primary: true },
  { city: 'Karak', postalCode: '27200', area: 'Karak GPO', primary: true },
  { city: 'Tank', postalCode: '29430', area: 'Tank GPO', primary: true },
  { city: 'Lakki Marwat', postalCode: '28420', area: 'Lakki Marwat GPO', primary: true },
  // Balochistan
  { city: 'Quetta', postalCode: '87300', area: 'Quetta GPO', primary: true },
  { city: 'Gwadar', postalCode: '91200', area: 'Gwadar GPO', primary: true },
  { city: 'Turbat', postalCode: '92600', area: 'Turbat GPO', primary: true },
  { city: 'Khuzdar', postalCode: '89100', area: 'Khuzdar GPO', primary: true },
  { city: 'Sibi', postalCode: '82000', area: 'Sibi GPO', primary: true },
  { city: 'Loralai', postalCode: '84800', area: 'Loralai GPO', primary: true },
  { city: 'Zhob', postalCode: '85200', area: 'Zhob GPO', primary: true },
  { city: 'Chaman', postalCode: '86000', area: 'Chaman GPO', primary: true },
  { city: 'Hub', postalCode: '90250', area: 'Hub GPO', primary: true },
  // AJK & GB
  { city: 'Muzaffarabad', postalCode: '13100', area: 'Muzaffarabad GPO', primary: true },
  { city: 'Mirpur', postalCode: '10250', area: 'Mirpur GPO', primary: true },
  { city: 'Kotli', postalCode: '11100', area: 'Kotli GPO', primary: true },
  { city: 'Rawalakot', postalCode: '12350', area: 'Rawalakot GPO', primary: true },
  { city: 'Bagh', postalCode: '12500', area: 'Bagh GPO', primary: true },
  { city: 'Gilgit', postalCode: '15700', area: 'Gilgit GPO', primary: true },
  { city: 'Skardu', postalCode: '16100', area: 'Skardu GPO', primary: true },
];

/** All registered Pakistani bank IBAN codes (SBP / SWIFT BIC prefix). */
const BANKS = [
  { code: 'ABPA', name: 'Allied Bank Limited' },
  { code: 'AIIN', name: 'Al Baraka Bank (Pakistan) Limited' },
  { code: 'ALFH', name: 'Bank Alfalah Limited' },
  { code: 'ASCM', name: 'Askari Bank Limited' },
  { code: 'BAHL', name: 'Bank Al Habib Limited' },
  { code: 'BKIP', name: 'BankIslami Pakistan Limited' },
  { code: 'BPUN', name: 'The Bank of Punjab' },
  { code: 'DUIB', name: 'Dubai Islamic Bank Pakistan Limited' },
  { code: 'FAYS', name: 'Faysal Bank Limited' },
  { code: 'FWOM', name: 'First Women Bank Limited' },
  { code: 'HABB', name: 'Habib Bank Limited' },
  { code: 'JSBL', name: 'JS Bank Limited' },
  { code: 'KHYB', name: 'The Bank of Khyber' },
  { code: 'MCIB', name: 'MCB Islamic Bank Limited' },
  { code: 'MPBL', name: 'Habib Metropolitan Bank Limited' },
  { code: 'MUCB', name: 'MCB Bank Limited' },
  { code: 'MEZN', name: 'Meezan Bank Limited' },
  { code: 'NBPA', name: 'National Bank of Pakistan' },
  { code: 'NIBP', name: 'NIB Bank Limited' },
  { code: 'SCBL', name: 'Standard Chartered Bank (Pakistan) Limited' },
  { code: 'SILK', name: 'Silkbank Limited' },
  { code: 'SMEP', name: 'Summit Bank Limited' },
  { code: 'UNIL', name: 'United Bank Limited' },
  { code: 'SAMB', name: 'Samba Bank Limited' },
  { code: 'SAUD', name: 'Saudi Pak Industrial Investment Bank' },
  { code: 'CITI', name: 'Citibank N.A. Pakistan' },
  { code: 'ICBK', name: 'Industrial and Commercial Bank of China' },
  { code: 'MSHQ', name: 'Mashreq Bank Pakistan' },
  { code: 'DEUT', name: 'Deutsche Bank AG' },
  { code: 'BARC', name: 'Barclays Bank PLC' },
  { code: 'SBPP', name: 'State Bank of Pakistan' },
  { code: 'TMFB', name: 'Telenor Microfinance Bank (Easypaisa)' },
  { code: 'JCMA', name: 'Mobilink Microfinance Bank (JazzCash)' },
  { code: 'NRSP', name: 'NRSP Microfinance Bank' },
  { code: 'FMFB', name: 'First MicroFinance Bank' },
  { code: 'APNA', name: 'Apna Microfinance Bank' },
  { code: 'KMBL', name: 'Khushhali Microfinance Bank' },
  { code: 'FINC', name: 'FINCA Microfinance Bank' },
  { code: 'UMBL', name: 'U Microfinance Bank' },
  { code: 'PAKB', name: 'Pak Oman Microfinance Bank' },
  { code: 'TAMW', name: 'Tameer Microfinance Bank' },
  { code: 'SIND', name: 'Sindh Bank Limited' },
  { code: 'SONE', name: 'Soneri Bank Limited' },
  { code: 'BIPL', name: 'Bank of Islamabad Limited' },
  // Legacy aliases used in older datasets
  { code: 'NBPB', name: 'National Bank of Pakistan', aliasOf: 'NBPA' },
  { code: 'MCBL', name: 'MCB Bank Limited', aliasOf: 'MUCB' },
  { code: 'UNIL', name: 'United Bank Limited' },
].filter((bank, index, arr) => {
  // Dedupe UNIL
  return arr.findIndex((b) => b.code === bank.code) === index;
}).sort((a, b) => a.code.localeCompare(b.code));

function writeJson(name, data) {
  const path = join(dataDir, name);
  writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
  console.log(`Wrote ${name}: ${Array.isArray(data) ? data.length : 'object'} entries`);
}

writeJson('districts.json', districts);
writeJson('cities.json', cities);
writeJson('postal-codes.json', POSTAL_CODES);
writeJson('banks.json', BANKS.map(({ code, name }) => ({ code, name })));

console.log(`\nSummary:`);
console.log(`  Districts: ${districts.length}`);
console.log(`  Cities: ${cities.length}`);
console.log(`  Postal codes: ${POSTAL_CODES.length}`);
console.log(`  Banks: ${BANKS.length}`);
